"use client"
import React, { useState, useEffect } from "react"
import { api } from "../../../../lib/api-client"
import { Button } from "../../../../components/ui/button"
import { ArrowLeft, Printer } from "lucide-react"
import { useRouter } from "next/navigation"

export default function SaleReceiptPage({ params }: { params: { id: string } }) {
  const [sale, setSale] = useState<any>(null)
  const [loading, setLoading] = useState(true)
  const router = useRouter()

  useEffect(() => {
    fetchSale()
  }, [])

  const fetchSale = async () => {
    try {
      const res = await api.get(`/sales/${params.id}`)
      setSale(res.data)
    } catch (error) {
      console.error("Failed to fetch sale", error)
    } finally {
      setLoading(false)
    }
  }

  if (loading) return <div className="p-8 text-center text-slate-500">Loading receipt...</div>
  if (!sale) return <div className="p-8 text-center text-destructive">Receipt not found</div>

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <div className="flex items-center justify-between no-print">
        <Button variant="ghost" onClick={() => router.push("/admin/sales")} className="text-slate-500 hover:text-slate-900">
          <ArrowLeft className="w-4 h-4 mr-2" /> Back to History
        </Button>
        <Button onClick={() => window.print()} className="bg-slate-900 text-white hover:bg-slate-800 shadow-sm interaction-bounce">
          <Printer className="w-4 h-4 mr-2" /> Print Receipt
        </Button>
      </div>

      <div className="solid-elevated p-8 bg-white print:p-0 print:border-none print:shadow-none">
        {/* Receipt Header */}
        <div className="text-center mb-8 border-b border-dashed border-slate-300 pb-8">
          <h1 className="text-2xl font-bold text-slate-900 tracking-tight">MY BUSINESS OS</h1>
          <p className="text-sm text-slate-500 mt-1">Store Receipt</p>
          
          <div className="mt-6 flex flex-col gap-1 text-sm text-slate-600">
            <p><strong>Receipt #:</strong> {sale.saleNumber}</p>
            <p><strong>Date:</strong> {new Date(sale.createdAt).toLocaleString()}</p>
            <p><strong>Cashier:</strong> {sale.createdByUserId}</p>
          </div>
        </div>

        {/* Items */}
        <table className="w-full text-sm text-slate-600 mb-8">
          <thead>
            <tr className="border-b border-slate-200">
              <th className="py-2 text-left font-semibold">Item</th>
              <th className="py-2 text-right font-semibold">Qty</th>
              <th className="py-2 text-right font-semibold">Price</th>
              <th className="py-2 text-right font-semibold">Total</th>
            </tr>
          </thead>
          <tbody>
            {sale.lines?.map((line: any) => (
              <tr key={line.id} className="border-b border-slate-100 last:border-0">
                <td className="py-3 text-slate-900">{line.productId}</td>
                <td className="py-3 text-right tabular-nums">{Number(line.quantity)}</td>
                <td className="py-3 text-right tabular-nums">৳{Number(line.unitPrice).toLocaleString()}</td>
                <td className="py-3 text-right tabular-nums font-medium text-slate-900">৳{Number(line.lineTotal).toLocaleString()}</td>
              </tr>
            ))}
          </tbody>
        </table>

        {/* Totals */}
        <div className="border-t border-slate-200 pt-4 space-y-2 text-sm">
          <div className="flex justify-between text-slate-600">
            <span>Subtotal</span>
            <span className="tabular-nums">৳{Number(sale.subtotal).toLocaleString()}</span>
          </div>
          {Number(sale.discount) > 0 && (
            <div className="flex justify-between text-rose-500">
              <span>Discount</span>
              <span className="tabular-nums">- ৳{Number(sale.discount).toLocaleString()}</span>
            </div>
          )}
          <div className="flex justify-between text-lg font-bold text-slate-900 pt-2 border-t border-slate-200 mt-2">
            <span>Total</span>
            <span className="tabular-nums">৳{Number(sale.total).toLocaleString()}</span>
          </div>
        </div>
        
        <div className="mt-8 text-center text-xs text-slate-400 border-t border-dashed border-slate-300 pt-8">
          <p>Thank you for your business!</p>
          <p className="mt-1">Generated by My Business OS</p>
        </div>
      </div>
    </div>
  )
}
